### ISSUE TITLE
[using_ec2_spot_instances_with_eks/jenkins] - jenkins spot ignored by cluster-autoscaler

### ISSUE THREAD

**Issue by marcindulak** [awslabs/ec2-spot-workshops#103]
The jenkins spot instances seem ignored by the cluster-autoscaler.

The `spot_nodegroup_jenkins.yml` [nodegroup](https://github.com/awslabs/ec2-spot-workshops/blob/ef471e29d1c2b93f3c54db4ff384513ffbcc5e82/content/using_ec2_spot_instances_with_eks/jenkins/setup_agents.md) does not include the tags required by the [cluster-autoscaler](https://github.com/awslabs/ec2-spot-workshops/blob/ef471e29d1c2b93f3c54db4ff384513ffbcc5e82/content/using_ec2_spot_instances_with_eks/scaling/deploy_ca.md) `k8s.io/cluster-autoscaler/enabled: true` and `k8s.io/cluster-autoscaler/eksworkshop-eksctl: owned`.

Another issue is that the requirement of a cluster-autoscaler is not stated in the introduction to [Running Jenkins jobs - optional module](https://github.com/awslabs/ec2-spot-workshops/blob/ef471e29d1c2b93f3c54db4ff384513ffbcc5e82/content/using_ec2_spot_instances_with_eks/jenkins/_index.md).

Please try to reproduce.

**Comment by ranshn** [comment]
Hello, many thanks for reporting this issue. we resolved a couple of problems with the Jenkins module in the EKS/Spot workshop following your report. you can see the details in #104 and please let us know if you're still facing any issues.
