### ISSUE TITLE
Update Auto Scaling workshops to use Capacity Rebalancing

### ISSUE THREAD

**Issue by ivallhon** [awslabs/ec2-spot-workshops#134]
[Running EC2 Workloads at scale with Auto Scaling groups](https://ec2spotworkshops.com/running-amazon-ec2-workloads-at-scale.html) and [EC2 Auto Scaling with multiple instance types and purchase options](https://ec2spotworkshops.com/ec2-auto-scaling-with-multiple-instance-types-and-purchase-options.html) need to be updated to leverage [Auto Scaling Capacity Rebalancing](https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-ec2-auto-scaling-ec2-fleet-and-spot-fleet-announce-capacity-rebalancing-for-ec2-spot-instances/).

**Comment by ruecarlo** [comment]
This has been closed right ?  Closing this request
