### ISSUE TITLE
 Running EC2 Workloads at Scale lab which prevents Code Deploy from successfully deploying to all EC2 instances.

### ISSUE THREAD

**Issue by ssbhat** [awslabs/ec2-spot-workshops#143]
At this URL: https://ec2spotworkshops.com/running-amazon-ec2-workloads-at-scale/deploy_app_codedeploy.html
Between steps 4 and 5, participants needs to change 
Ec2-spot-workshops\workshops\running-amazon-ec2-workloads-at-scale\koel\composer.json
Line 30 is now case sensitive and the “S” in stream needs to be lower case.
From: "mikey179/vfsStream": "^1.6"
To: "mikey179/vfsstream": "^1.6"
 
This can either be corrected in the lab instructions or by updating the original koel package.

**Comment by ruecarlo** [comment]
Thanks @ssbhat will check.

**Comment by neilkuan** [comment]
I meet the same issue, I to change `"mikey179/vfsStream": "^1.6"` to `"mikey179/vfsstream": "^1.6"` in composer.json to this solve issue.
