### ISSUE TITLE
Invalid base64 error when calling aws ec2 import-key-pair using AWS CLI version 2

### ISSUE THREAD

**Issue by fumikoba** [awslabs/ec2-spot-workshops#48]
**Issue**
When you execute the following commands to import key pair using AWS CLI version 2, it fails with "Invalid base64" error.
https://ec2spotworkshops.com/using_ec2_spot_instances_with_eks/prerequisites/sshkey.html
`aws ec2 import-key-pair --key-name "eksworkshop" --public-key-material file://~/.ssh/id_rsa.pub
`

**Workaround**
Use fileb:// in order for AWS CLI version 2 to treat the file content as unencoded bibary.
https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binaryparam
`aws ec2 import-key-pair --key-name "eksworkshop" --public-key-material fileb://~/.ssh/id_rsa.pub
`

**Comment by ruecarlo** [comment]
Thanks for raising the issue Fumi. I'll be raising a PR to change that.

**Comment by matty1979** [comment]
Just commenting to bring this higher up search engine finds. This correctly fixes the issue of push a created key to AWS

**Comment by Cloud-Mak** [comment]
wow...I can not belive this is still any issue. @ruecarlo have you raised PR for this?
