### ISSUE TITLE
"InstanceProfileARN" OutputKey doesn't exist

### ISSUE THREAD

**Issue by fumikoba** [awslabs/ec2-spot-workshops#49]
**Issue**
Following commands failed because "InstanceProfileARN" OutputKey doesn't exist in Output.
https://ec2spotworkshops.com/using_ec2_spot_instances_with_eks/eksctl/test.html

`INSTANCE_PROFILE_ARN=$(aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[].Outputs[] | select(.OutputKey=="InstanceProfileARN") | .OutputValue')`

`ROLE_NAME=$(aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[].Outputs[] | select(.OutputKey=="InstanceRoleARN") | .OutputValue' | cut -f2 -d/)`

**Workaround**
Use following commands to obtain IAM role name and its ARN assigned to the node.

`ROLE_NAME=$(aws cloudformation  describe-stack-resources --stack-name $STACK_NAME | jq -r '.StackResources[] | select(.LogicalResourceId=="NodeInstanceRole") | .PhysicalResourceId')`

`INSTANCE_PROFILE_ARN=$(aws iam get-role --role-name $ROLE_NAME | jq -r '.[].Arn')`

**Comment by ruecarlo** [comment]
In the end I'll be settling for  the following. Now that we have moved to managed nodegroups the cloudformation template outputs are not the right way to capture attributes. I've moved them straight to a call to the cli/api to query for the same.

```bash
NODE_GROUP_NAME=$(eksctl get nodegroup --cluster eksworkshop-eksctl -o json | jq -r '.[].Name')
ROLE_NAME=$(aws eks describe-nodegroup --cluster-name eksworkshop-eksctl --nodegroup-name $NODE_GROUP_NAME | jq -r '.nodegroup["nodeRole"]' | cut -f2 -d/)
echo "export ROLE_NAME=${ROLE_NAME}" >> ~/.bash_profile
```
