### ISSUE TITLE
[LAUNCHING EC2 SPOT INSTANCES] - Requires an in-depth update

### ISSUE THREAD

**Issue by ruecarlo** [awslabs/ec2-spot-workshops#93]
Currently the workshop points to execution of commands with inputs that may fail depending on the region they run, as well as references to AMI's that are not valid anymore and a few other similar errors. This workshop is intended to be updated to :
 - Add a Cloud9 environment from which to run the commands
 - Move all examples to CLI
 - Adapt all the changes to use best practices
 - Educate on pools and diversification best practices as well as well as differences between API's and when should be used.

**Comment by horsfieldsa** [comment]
Working in this with senkinnar@ and Ananth

**Comment by ruecarlo** [comment]
Just completed it on pull request https://github.com/awslabs/ec2-spot-workshops/pull/151 .  needed it fixed for a workshop covering this topics.
